services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=test
  flyway:
    image: flyway/flyway
    environment:
      - FLYWAY_URL=jdbc:postgresql://db/test
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=asdf
      - FLYWAY_CONNECT_RETRIES=60
      - FLYWAY_CLEAN_DISABLED=false
    command: clean migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db