---
services:
  app:
    build: ./template
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=test
  flyway:
    build: ./database
    environment:
      - FLYWAY_URL=jdbc:postgresql://db/test
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=asdf
      - FLYWAY_CONNECT_RETRIES=60
      - FLYWAY_CLEAN_DISABLED=false
    command: clean migrate
    depends_on:
      - db