---
spring:
  config:
    import: optional:file:./config/test.yaml
#  datasource:
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password: asdf
#    driver-class-name: org.postgresql.Driver
server:
  port: 8080
  shutdown: graceful
management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "health"
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true