---
name: Java CI with Gradle
on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew check
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-context:
          - template
          - database
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.node-version }}
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.node-version }}
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.node-version }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/sampleapp:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
      - name: Push ${{ matrix.node-version }}
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.node-version }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.node-version }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max